# Generated by Django 5.0.3 on 2024-03-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MainDataSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheme_name", models.CharField(max_length=100)),
                ("min_sip", models.IntegerField()),
                ("min_lumpsum", models.IntegerField()),
                ("expense_ratio", models.FloatField()),
                ("fund_size_cr", models.FloatField()),
                ("fund_age_yr", models.IntegerField()),
                ("risk_level", models.IntegerField()),
                ("rating", models.IntegerField()),
                ("category", models.CharField(max_length=100)),
                ("sub_category", models.CharField(max_length=100)),
                ("returns_1yr", models.FloatField()),
                ("returns_3yr", models.FloatField()),
                ("returns_5yr", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="SelectedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheme_name", models.CharField(max_length=100)),
                ("risk_level", models.IntegerField()),
                ("risk_category", models.CharField(max_length=100)),
                ("returns_1yr", models.FloatField()),
                ("returns_3yr", models.FloatField()),
                ("returns_5yr", models.FloatField()),
            ],
        ),
    ]
